### ISSUE TITLE
About the package diff

### ISSUE THREAD

**Issue by 196728abc** [AleMorales/DynamicPhotosynthesis#1]
Dear Dr. Morales. In the Project "DynamicPhotosynthesis", A problem was happened that there is no package named ‘diff’. I read the sources codes and found that in the file "nlfit-bbox.R", the package "diff" used there. But the package "diff" is not the base package in R and there is no an about clue about diff in this project. So could you help this?

**Comment by AleMorales** [comment]
Indeed, it seems the package is missing from the folder "Packages" (these were local packages I developed for the project, never published). Depending on what you need to use the model for, you will not needed it (this is only needed to estimate the different parameter values for the original paper, as a replacement for nls, it is not needed to run simulations with the model of dynamic photosynthesis). In any case, I will upload a correct version to this repository asap as this may be preventing installation. Thanks for pointing it out and sorry for the annoyance!

**Comment by AleMorales** [comment]
I added the diff package to the dependencies and fix other outdated packages. There might some dependencies still needed for the calibration of the model but I have added all the intermediate results from the original analysis, so you can skip those initial scripts and jump directly to the simulation scripts.
